"""
build_art.py — download famous public-domain paintings from Wikimedia Commons,
convert each to an ASCII grid, generate a matching faux-C 'renderer' source, and
emit src/paintings.js for the front-end.

Run:  python tools/build_art.py
"""
import base64, io, json, os, ssl, sys, urllib.parse, urllib.request, warnings
from PIL import Image
import img2ascii

warnings.simplefilter("ignore")
Image.MAX_IMAGE_PIXELS = None  # trusted public-domain sources

COLS, ROWS = 168, 92          # hi-detail calibrated-mono grid
WIDTH = 1400  # download width from Commons (keeps it light)
FLOOR = 0.02      # tiny luminance floor (alpha/black_cut do the real masking)
BLACK_CUT = 24    # source RGB max-channel < this -> background (blank cell)
CUSTOM = "tools/custom"       # drop bg-removed PNGs here as <id>.png to override
CTX = ssl.create_default_context()

# Gallery set — sources are the hand-prepared black-background PNGs in
# tools/custom/<id>.png (no Wikimedia download needed).
PAINTINGS = [
    dict(id="pearl",    title="Girl with a Pearl Earring", ko="진주 귀걸이를 한 소녀",
         artist="Johannes Vermeer",   year="1665", files=[]),
    dict(id="klimt",    title="The Kiss",                  ko="키스",
         artist="Gustav Klimt",       year="1908", files=[]),
    dict(id="napoleon", title="Napoleon Crossing the Alps", ko="알프스를 넘는 나폴레옹",
         artist="Jacques-Louis David", year="1801", files=[]),
    dict(id="bull",     title="Bull",                      ko="황소",
         artist="Lee Jung-seop",      year="1953", files=[]),
    dict(id="monalisa", title="Mona Lisa",                 ko="모나리자",
         artist="Leonardo da Vinci",  year="c.1503", files=[]),
]


def download(filename):
    fp = urllib.parse.quote(filename)
    url = f"https://commons.wikimedia.org/wiki/Special:FilePath/{fp}?width={WIDTH}"
    req = urllib.request.Request(url, headers={
        "User-Agent": "ArtFormContestPrototype/1.0 (educational; contact ghkdtksgo051@gmail.com)"})
    return urllib.request.urlopen(req, timeout=90, context=CTX).read()


def c_source(p):
    """A decorative, painting-specific C 'renderer' shown typing in the left pane."""
    pal = img2ascii.PALETTE.replace("\\", "\\\\").replace('"', '\\"')
    sym = p["id"].upper()
    return f"""#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define W {COLS}
#define H {ROWS}

/* {p['title']} — {p['artist']}, {p['year']} */
static const char *PALETTE =
  "{pal}";

/* map luminance [0,255] -> palette glyph */
static char glyph(int lum) {{
  int n = strlen(PALETTE) - 1;
  return PALETTE[lum * n / 255];
}}

int render_{p['id']}(void) {{
  FILE *f = fopen("{p['id']}.lum", "rb");
  if (!f) return 1;
  unsigned char px[H][W];
  fread(px, 1, W * H, f);
  for (int y = 0; y < H; y++) {{
    for (int x = 0; x < W; x++)
      putchar(glyph(px[y][x]));
    putchar('\\n');
  }}
  fclose(f);
  return 0;
}}

int main(void) {{
  fprintf(stderr, "rendering {p['title']}...\\n");
  return render_{p['id']}();
}}
"""


def color_b64(path):
    im = img2ascii.to_color_image(path, cols=COLS, rows=ROWS, floor=FLOOR, black_cut=BLACK_CUT)
    buf = io.BytesIO(); im.save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def source_path(p):
    """Prefer a hand-prepared (background-removed) image in tools/custom/."""
    for ext in (".png", ".webp", ".jpg", ".jpeg"):
        cand = os.path.join(CUSTOM, p["id"] + ext)
        if os.path.exists(cand):
            return cand, f"custom/{p['id']}{ext}"
    data = download_first(p)
    if data is None:
        return None, None
    tmp = f"tools/_{p['id']}.img"; open(tmp, "wb").write(data)
    return tmp, "(wikimedia)"


def download_first(p):
    for fn in p["files"]:
        try:
            return download(fn)
        except Exception as e:
            print(f"[..] {p['id']:9s} miss {fn}: {e}")
    return None


def main():
    out = []
    for p in PAINTINGS:
        path, used = source_path(p)
        if path is None:
            print(f"[FAIL] {p['id']} — no source", file=sys.stderr); continue
        art = img2ascii.to_ascii(path, cols=COLS, rows=ROWS, floor=FLOOR, black_cut=BLACK_CUT)
        color = color_b64(path)
        print(f"[ok] {p['id']:9s} <- {used}")
        out.append(dict(id=p["id"], title=p["title"], ko=p["ko"],
                        artist=p["artist"], year=p["year"],
                        art=art, color=color))

    js = "// AUTO-GENERATED by tools/build_art.py — do not edit by hand.\n"
    js += "window.PAINTINGS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
    open("src/paintings.js", "w", encoding="utf-8").write(js)
    print(f"\nwrote src/paintings.js  ({len(out)} paintings, {len(js)//1024} KB)")


if __name__ == "__main__":
    main()
